### PR TITLE
Some rubocop fixes

### PR DESCRIPTION
**Pull request by arthurmde**
This MR reduces some offenses detected by rubocop. More specifically, I fixed the following problems
```sh
Gemfile:2:1: C: Add an empty line after magic comments.
source 'https://rubygems.org'
^
Gemfile:5:1: C: Gems should be sorted in an alphabetical order within their section of the Gemfile. Gem paint should appear before whirly.
gem 'paint'
^^^^^^^^^^^
Gemfile:6:1: C: Gems should be sorted in an alphabetical order within their section of the Gemfile. Gem clipboard should appear before paint.
gem 'clipboard'
^^^^^^^^^^^^^^^
Gemfile:8:1: C: Gems should be sorted in an alphabetical order within their section of the Gemfile. Gem http should appear before rex-text.
gem 'http'
^^^^^^^^^^
Rakefile:1:9: C: Prefer single-quoted strings when you don't need string interpolation or special symbols.
require "bundler/gem_tasks"
        ^^^^^^^^^^^^^^^^^^^
Rakefile:2:9: C: Prefer single-quoted strings when you don't need string interpolation or special symbols.
require "rspec/core/rake_task"
        ^^^^^^^^^^^^^^^^^^^^^^
Rakefile:6:6: C: Use the new Ruby 1.9 hash syntax.
task :default => :spec
     ^^^^^^^^^^^
rise-cli.gemspec:8:19: C: Use %w or %W for an array of words.
  s.executables = ['rise', 'setup', 'console']
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rise-cli.gemspec:10:19: C: Prefer single-quoted strings when you don't need string interpolation or special symbols.
  s.summary     = "Simple serverless website deployment"
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rise-cli.gemspec:15:5: W: } at 15, 4 is not aligned with s.files       = git ls-files.split($/).reject { |file| at 13, 2.
    }
    ^
rise-cli.gemspec:18:12: C: Unnecessary spacing detected.
  s.license       = 'MIT'
           ^^^^^^
rise-cli.gemspec:18:19: C: Operator = should be surrounded by a single space.
  s.license       = 'MIT'
                  ^
lib/core/util.rb:16:1: C: Extra empty line detected at module body beginning.
lib/core/util.rb:20:14: C: Rename is_first_run? to first_run?.
    def self.is_first_run?
             ^^^^^^^^^^^^^
lib/core/util.rb:57:7: C: Missing space after #.
      #TODO Reimplement when the backend server actually works
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/core/util.rb:57:8: C: Annotation keywords like TODO should be all upper case, followed by a colon, and a space, then a note describing the problem.
      #TODO Reimplement when the backend server actually works
       ^^^^^
lib/core/util.rb:59:7: C: Missing space after #.
      #print Paint['1. Log in\n2. Sign up\n  > ', :bold]
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/core/util.rb:60:7: C: Missing space after #.
      #while (choice = gets.chomp!)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/core/util.rb:71:7: C: Missing space after #.
      #end
      ^^^^
lib/core/util.rb:72:1: C: Extra empty line detected at method body end.
lib/core/util.rb:74:1: C: Extra empty line detected at module body end.

```

### CODE REVIEW

**Comment by cbrnrd** [comment]
Thanks for contributing! The changes look good, but in order for me to merge your changes you need to update `Gemfile` on your fork.

**Comment by arthurmde** [comment]
@cbrnrd I just fixed it. It seems that this MR adds a codeclimate issue. Could you please take a look on it and tell me if you want to remove this **TODO**?

**Comment by cbrnrd** [comment]
That’s odd, it’s saying that an old TODO is new. Yeah you can remove it to get rid of the error and i’ll add it to the TODO.txt

**Comment by cbrnrd** [comment]
Actually, scratch my previous comment. I'll merge your changes just to get it passing rubocop and I'll remove the TODO

**Pull request merged**
